In [1]:
import numpy as np

In [2]:
array_1 = np.array([1,2,3,4,5])

In [3]:
array_1

array([1, 2, 3, 4, 5])

In [4]:
#Two dimentional array
array_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
array_from_tuple = np.array((1,2,3,4))

In [11]:
array_from_tuple

array([1, 2, 3, 4])

In [13]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. note::
            

In [17]:
np.random.random([5,3])

array([[0.61942964, 0.47819291, 0.4348412 ],
       [0.88026792, 0.20522232, 0.72972241],
       [0.77783504, 0.76627608, 0.35694761],
       [0.01492974, 0.86986332, 0.03012873],
       [0.1135113 , 0.66471243, 0.84912147]])

In [19]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [23]:
np.linspace(15,20,25)

array([15.        , 15.20833333, 15.41666667, 15.625     , 15.83333333,
       16.04166667, 16.25      , 16.45833333, 16.66666667, 16.875     ,
       17.08333333, 17.29166667, 17.5       , 17.70833333, 17.91666667,
       18.125     , 18.33333333, 18.54166667, 18.75      , 18.95833333,
       19.16666667, 19.375     , 19.58333333, 19.79166667, 20.        ])

In [24]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passe

In [27]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [28]:
random_array = np.random.random([1000,300])

In [37]:
random_array[1,]

array([0.29041857, 0.51326876, 0.89946699, 0.762703  , 0.72909533,
       0.55665998, 0.47039061, 0.81806212, 0.89821945, 0.39336291,
       0.34327049, 0.19540129, 0.80139213, 0.08325844, 0.59637385,
       0.12053965, 0.19564477, 0.05561025, 0.00102676, 0.25986411,
       0.13638448, 0.42841562, 0.41404562, 0.17790419, 0.33488232,
       0.96251183, 0.78635917, 0.08940326, 0.35093054, 0.04735554,
       0.28873319, 0.18469176, 0.15991529, 0.25882962, 0.01081521,
       0.68605736, 0.51862472, 0.93585578, 0.96519172, 0.98400604,
       0.6932909 , 0.7951891 , 0.77951654, 0.80464157, 0.60647517,
       0.73091869, 0.11386372, 0.63797268, 0.37215406, 0.77150939,
       0.69381728, 0.60581786, 0.03288083, 0.86351264, 0.66351811,
       0.85873983, 0.20707549, 0.42729001, 0.12971911, 0.89359398,
       0.45403483, 0.49619592, 0.69810529, 0.86393967, 0.52135995,
       0.25510077, 0.45417541, 0.6617016 , 0.28610694, 0.04542319,
       0.59404104, 0.70798889, 0.83125795, 0.67771476, 0.90812

In [43]:
np.arange(21).reshape(3,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])